version: '3.9'

services:
  frontend:
    image: node:17-alpine
    container_name: portfolio-frontend
    build: .
    volumes:
      - ./portfolio/:/portfolio/
    ports:
      - 8080:8080
    command: npm run serve

    